#! /usr/bin/env python

import cgi
import cgitb
cgitb.enable()
data = cgi.FieldStorage()

import json

with open("/home/http/allSettings.json", "w") as fd:
    payload = {
        "url": data["url"].value,
        "token": data["token"].value
    }
    json.dump(payload, fd)    

print
print '{ "success": "true" }'
